### ISSUE TITLE
Error local variable 'full_output' referenced before assignment

### ISSUE THREAD

**Issue by tcxia** [SqueezeAILab/LLMCompiler#14]
hi，I used pre-training Qwen  and this error occurred
`class Qwen_LLM(LLM):
    tokenizer: AutoTokenizer = None
    model: AutoModelForCausalLM = None

    def __init__(self, model_path: str):
        super().__init__()
        print("Qwen Loading")
        self.tokenizer = AutoTokenizer.from_pretrained(
            model_path, trust_remote_code=True
        )
        self.model = AutoModelForCausalLM.from_pretrained(
            model_path, device_map="auto", trust_remote_code=True
        ).eval()
        self.model.generation_config = GenerationConfig.from_pretrained(
            model_path, trust_remote_code=True
        )
        self.model.generation_config.do_sample = False # greedy

    def _call(self, prompt: str, stop: Optional[List[str]] = None, run_manager: Optional[CallbackManagerForLLMRun] = None, **kwargs: Any):
        # stop = ["Observation:", "Observation:\n"]
        # react_stop_words_tokens = [self.tokenizer.encode(stop_) for stop_ in stop]
        # response, _ = self.model.chat(self.tokenizer, prompt, history=None, stop_words_ids=react_stop_words_tokens)
        # response, _ = self.model.chat(self.tokenizer, prompt)
        prompt_ids = torch.tensor([self.tokenizer.encode(prompt)]).to(self.model.device)
        output = self.model.generate(prompt_ids, max_new_tokens=512, pad_token_id=self.tokenizer.eos_token_id).tolist()[0]
        response = self.tokenizer.decode(output, errors="ignore")
        return response

    @property
    def _llm_type(self) -> str:
        return "QwenLLM"`

**Comment by SuhongMoon** [comment]
For the open source model, please try vLLM.

**Comment by kssteven418** [comment]
Hi, LLMCompiler currently only supports vLLM for using custom models. That said, you need to set up a vLLM server that runs the QWEN model, following the official vLLM documentation. LLMCompiler works as a client that pings the server once you do so.
